### PR TITLE
WIP exploring building uiSelect and uiMention sub-components

### PR DESCRIPTION
**Pull request by ProLoser**
I would like to explore this design pattern for the future of
ui-select, but the major feature I need is multiple select and
ui-select is terribly bloated. I am hoping that laying this groundwork
will start a pattern of highly modular and versatile select
components that can keep the code light at the same time.

### CODE REVIEW

**Comment by ProLoser** [comment]
Haven't tested this yet. First want to build a basic select functionality with `ui-select`, then make it behave properly as `ui-mention`, and finally add in (possibly in another PR) multi-select.

This was built by splitting the `ui-mention` controller in half, so theoretically this should be achievable, however will need to explore about elegant methods / alternatives to monkey-patching the `uiSelect` controller.

**Comment by ProLoser** [comment]
Please peruse the WIP source and provide feedback: https://github.com/angular-ui/ui-mention/tree/ui-select/src

**Comment by ProLoser** [comment]
Extra thought: since ui-mention needs the ability to have multiple items selected, perhaps it should depend on uiSelectMultiple. The only thing is if uiSelectMultiple is mostly focused on rendering then it may not be worth it

**Comment by Jefiozie** [comment]
Do you need some help on this? Trying to help on the ui-select project maybe I can also help here?

**Comment by ProLoser** [comment]
@Jefiozie I'm not really active anymore but if you'd like to work on what I was exploring I can add you as a collaborator. My intention was to rebuild ui-mention and ui-select in a way that they were both modular and stackable and worked together. However I am not using ng2 so I don't know how much of that code exploration is vestigial.

It was mostly designed around the concept of composeable, modular, abstracted components. Then you mix in feature components like multi-select and mention highlighting, etc.

**Comment by ProLoser** [comment]
The main idea is instead of having people pass EVERY single configuration value in their DOM markup as an attribute, they use our components as abstract or basic implementations which they are expected to extend into proprietary implementations of the components where they can override behavior as desired. This way the HTML markup is streamlined and simplified for their app, and new functionality doesn't have to be merged upstream thereby cluttering the abstract library with superfluous features.

**Comment by Jefiozie** [comment]
@ProLoser , like the idea you are describing. Also love the idea of rewriting ui-select as there are a lot of things that can be better. I also don't use ng2 but thought this would be a good way to learn and contribute to a project.

Still I can have a shot on rewrite ui-select for ng2. Any tips where to start?

**Comment by ProLoser** [comment]
I don't use ng2 so I don't know where to start sadly.

**Pull request closed without merging**
