### PR TITLE
Fixed dependency injection breaking on minification

### PR DESCRIPTION
**Pull request by handonam**
A minification gotcha with angular

https://scotch.io/tutorials/declaring-angularjs-modules-for-minification

This fixed my mention system breaking in production because it couldn't find `eProvider <- e <- uiMention`, with "e" being the uglified variable `$element`

### CODE REVIEW

**Comment by handonam** [comment]
@ProLoser mind taking a look here?

**Comment by ProLoser** [comment]
This won't be accepted. If you'd like, you can submit a PR with this instead: https://www.npmjs.com/package/gulp-ng-annotate which requires merely tweaking the gulpfile and package. That way all of the annotation is done at build time.

**Comment by handonam** [comment]
@ProLoser I reset back one commit and force pushed this commit for ya

**Comment by ProLoser** [comment]
:+1:

**Comment by handonam** [comment]
We might need to update the bower version to get this to work fyi. Bower resolves to the commit before this.

**Comment by ProLoser** [comment]
cd434a02b2f378b3b1f11d40df2d44762c414cf6

**Pull request merged**
